import { test } from 'node:test';
import assert from 'node:assert/strict';
import { toYaml, slugForUrl, githubNewFileUrl, MAX_GITHUB_URL_LENGTH } from '../src/yaml.js';

const CFG = {
  id: 'example-blog',
  name: 'Example "Blog"',
  description: 'Unofficial RSS feed scraped from https://example.com/blog',
  listing_url: 'https://example.com/blog',
  base_url: 'https://example.com',
  item_selector: 'div.post-card',
  link_selector: 'a',
  title_selector: 'h2[class*="title"]',
  date_selector: null,
  category_selector: "span[data-kind='tag']",
};

test('toYaml snapshot: key order, quoting, omitted unpicked selectors', () => {
  assert.equal(
    toYaml(CFG, { date: '2026-09-18' }),
    `# Generated by the feed-scraper selector-picker bookmarklet
# from https://example.com/blog on 2026-09-18.

id: example-blog
name: "Example \\"Blog\\""
description: "Unofficial RSS feed scraped from https://example.com/blog"
listing_url: "https://example.com/blog"
base_url: "https://example.com"

item_selector: 'div.post-card'
link_selector: 'a'
title_selector: 'h2[class*="title"]'
category_selector: 'span[data-kind=''tag'']'

fetch_detail: true
max_items: 75

user_agent: "Mozilla/5.0 (compatible; PersonalSiteRSSBot/1.0; run by a single subscriber for personal use)"
`,
  );
});

test('slugForUrl: hostname minus www/TLD plus first path segment', () => {
  assert.equal(slugForUrl('https://www.anthropic.com/news'), 'anthropic-news');
  assert.equal(slugForUrl('https://blog.example.com/'), 'blog-example');
  assert.equal(slugForUrl('https://example.com/Posts_2026/page/2?x=1'), 'example-posts-2026');
});

test('githubNewFileUrl pre-fills path and content', () => {
  const { url, ok } = githubNewFileUrl('curiousstranger/feed-scraper', 'example-blog', 'id: x\n');
  assert.equal(ok, true);
  assert.equal(
    url,
    'https://github.com/curiousstranger/feed-scraper/new/main?filename=sites/example-blog.yaml&value=id%3A%20x%0A',
  );
});

test('githubNewFileUrl is not ok past the length limit', () => {
  const { url, ok } = githubNewFileUrl('o/r', 'x', 'y'.repeat(MAX_GITHUB_URL_LENGTH));
  assert.ok(url.length > MAX_GITHUB_URL_LENGTH);
  assert.equal(ok, false);
});
