// Site config → sites/<id>.yaml text, plus the GitHub "new file" link.

export const DEFAULT_USER_AGENT =
  'Mozilla/5.0 (compatible; PersonalSiteRSSBot/1.0; run by a single subscriber for personal use)';
export const MAX_GITHUB_URL_LENGTH = 8000;
const OPTIONAL_SELECTORS = ['link_selector', 'title_selector', 'date_selector', 'category_selector'];
const YAML_KEYWORDS = new Set(['yes', 'no', 'true', 'false', 'on', 'off', 'null']);

function doubleQuoted(s) {
  const escaped = String(s)
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
}

function singleQuoted(s) {
  return `'${String(s).replace(/'/g, "''")}'`;
}

// Mirrors scraper/run.py:SITE_ID_RE. The id names data/<id>.json and
// docs/feeds/<id>.xml, so nothing that could escape those directories.
const SITE_ID = /^[a-z0-9][a-z0-9-]*$/;

export function isValidSiteId(id) {
  return SITE_ID.test(String(id));
}

function shouldQuoteId(id) {
  // Quote if it doesn't match the safe pattern or is a YAML keyword
  return !/^[a-z][a-z0-9-]*$/.test(id) || YAML_KEYWORDS.has(id);
}

/** YAML in sites/anthropic-news.yaml key order; unpicked optional selectors omitted. */
export function toYaml(cfg, { date }) {
  const id = shouldQuoteId(cfg.id) ? doubleQuoted(cfg.id) : cfg.id;
  const lines = [
    '# Generated by the feed-scraper selector-picker bookmarklet',
    `# from ${cfg.listing_url} on ${date}.`,
    '',
    `id: ${id}`,
    `name: ${doubleQuoted(cfg.name)}`,
    `description: ${doubleQuoted(cfg.description)}`,
    `listing_url: ${doubleQuoted(cfg.listing_url)}`,
    `base_url: ${doubleQuoted(cfg.base_url)}`,
    '',
    `item_selector: ${singleQuoted(cfg.item_selector)}`,
  ];
  for (const key of OPTIONAL_SELECTORS) {
    if (cfg[key]) lines.push(`${key}: ${singleQuoted(cfg[key])}`);
  }
  lines.push('', 'fetch_detail: true', 'max_items: 75', '', `user_agent: ${doubleQuoted(DEFAULT_USER_AGENT)}`, '');
  return lines.join('\n');
}

/** Default site id: hostname labels minus www and TLD, plus the first path segment. */
export function slugForUrl(href) {
  const url = new URL(href);
  const labels = url.hostname.split('.').filter((l) => l !== 'www');
  if (labels.length > 1) labels.pop();
  const first = url.pathname.split('/').filter(Boolean)[0] ?? '';
  return [...labels, first]
    .join('-')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

/** {url, ok}: GitHub's pre-filled new-file page; ok is false past the length limit. */
export function githubNewFileUrl(repo, id, yaml) {
  const filename = encodeURIComponent(`sites/${id}.yaml`).replace(/%2F/g, '/');
  const url = `https://github.com/${repo}/new/main?filename=${filename}&value=${encodeURIComponent(yaml)}`;
  return { url, ok: url.length <= MAX_GITHUB_URL_LENGTH };
}
